[[redirects]]
  from = "/plugins/*"
  to = "/plugins"
  status = 200


[[redirects]]
  from = "/careers/*"
  to = "/careers"
  status = 200


[[redirects]]
    from = "/docs/integrations/android-integration"
    to = "/docs/libraries/android"


[[redirects]]
    from = "/docs/integrations/community"
    to = "/docs/libraries/community"


[[redirects]]
    from = "/docs/integrations/docusaurus-integration"
    to = "/docs/libraries/docusaurus"


[[redirects]]
    from = "/docs/integrations/elixir-integration"
    to = "/docs/libraries/elixir"


[[redirects]]
    from = "/docs/integrations/flutter-integration"
    to = "/docs/libraries/flutter"


[[redirects]]
    from = "/docs/integrations/gatsby-integration"
    to = "/docs/libraries/gatsby"


[[redirects]]
    from = "/docs/integrations/go-integration"
    to = "/docs/libraries/go"


[[redirects]]
    from = "/docs/integrations/ios-integration"
    to = "/docs/libraries/ios"


[[redirects]]
  from = "/docs/integrations/javascript-integration"
  to = "/docs/libraries/js"

[[redirects]]
    from = "/docs/integrations/js-integration"
    to = "/docs/libraries/js"


[[redirects]]
    from = "/docs/integrations/message-formatting"
    to = "/docs/libraries/message-formatting"


[[redirects]]
    from = "/docs/integrations/microsoft-teams"
    to = "/docs/libraries/microsoft-teams"


[[redirects]]
    from = "/docs/integrations/node-integration"
    to = "/docs/libraries/node"


[[redirects]]
    from = "/docs/integrations/php-integration"
    to = "/docs/libraries/php"


[[redirects]]
    from = "/docs/integrations/python-integration"
    to = "/docs/libraries/python"


[[redirects]]
    from = "/docs/integrations/react-native-integration"
    to = "/docs/libraries/react-native"


[[redirects]]
    from = "/docs/integrations/ruby-integration"
    to = "/docs/libraries/ruby"


[[redirects]]
    from = "/docs/integrations/rudderstack-integration"
    to = "/docs/libraries/rudderstack"


[[redirects]]
    from = "/docs/integrations/segment-integration"
    to = "/docs/libraries/segment"


[[redirects]]
    from = "/docs/integrations/sentry-integration"
    to = "/docs/libraries/sentry"


[[redirects]]
    from = "/docs/integrations/slack"
    to = "/docs/libraries/slack"


[[redirects]]
    from = "/handbook/company/structure"
    to = "/handbook/people/team-structure/why-small-teams"


[[redirects]]
    from = "/handbook/people/team"
    to = "/handbook/company/team"


[[redirects]]
    from = "/handbook/growth/customer-success"
    to = "/handbook/growth/customer-support"


[[redirects]]
    from = "/handbook/growth/customer-success"
    to = "/handbook/growth/customer-support"


[[redirects]]
    from = "/handbook/getting-started"
    to = "/handbook/getting-started/start-here"


[[redirects]]
    from = "/handbook/getting-started"
    to = "/handbook/getting-started/start-here"

[[redirects]]
    from = "/handbook/people/team-structure/user-experience"
    to = "/handbook/people/team-structure/core-experience"


[[redirects]]
    from = "/docs/plugins/build"
    to = "/docs/plugins/build/overview"


[[redirects]]
    from = "/docs/plugins/types"
    to = "/docs/plugins/build/types"

[[redirects]]
    from = "/docs/developing-locally"
    to = "/docs/contributing/developing-locally"


[[redirects]]
    from = "/docs/project-structure"
    to = "/docs/contributing/project-structure"


[[redirects]]
    from = "/docs/recognizing-contributions"
    to = "/docs/contributing/recognizing-contributions"


[[redirects]]
    from = "/docs/stack"
    to = "/docs/contributing/stack"


[[redirects]]
    from = "/docs/updating-documentation"
    to = "/docs/contributing/updating-documentation"
    
[[redirects]]
    from = "/docs/self-host/postgres-vs-clickhouse"
    to = "/docs/configuring-posthog/scaling-posthog"

[[redirects]]
    from = "/docs/self-host"
    to = "/docs/self-host/overview"

[[redirects]]
    from = "/docs/deployment"
    to = "/docs/self-host/overview#deploy"

[[redirects]]
    from = "/docs/self-host/configure"
    to = "/docs/self-host/overview#configure"

[[redirects]]
    from = "/docs/configuring-posthog"
    to = "/docs/self-host/configure"

[[redirects]]
    from = "/docs/features/log-in-with-github-gitlab"
    to = "/docs/user-guides/log-in-with-sso"

# Added: 2021-07-13
[[redirects]]
    from = "/docs/contributing/developing-locally"
    to = "/docs/contribute/developing-locally"

# Added: 2021-07-13
[[redirects]]
    from = "/docs/contributing"
    to = "/docs/contribute/overview"

# Added: 2021-07-13
[[redirects]]
    from = "/docs/contributing/project-structure"
    to = "/docs/contribute/project-structure"

# Added: 2021-07-13
[[redirects]]
    from = "/docs/contributing/recognizing-contributions"
    to = "/docs/contribute/recognizing-contributions"

# Added: 2021-07-13
[[redirects]]
    from = "/docs/contributing/stack"
    to = "/docs/contribute/stack"

# Added: 2021-07-13
[[redirects]]
    from = "/docs/contributing/updating-documentation"
    to = "/docs/contribute/updating-documentation"

# Added: 2021-07-13
[[redirects]]
    from = "/docs/libraries/android"
    to = "/docs/integrate/client/android"

# Added: 2021-07-13
[[redirects]]
    from = "/docs/libraries/flutter"
    to = "/docs/integrate/client/flutter"

# Added: 2021-07-13
[[redirects]]
    from = "/docs/libraries/ios"
    to = "/docs/integrate/client/ios"

# Added: 2021-07-13
[[redirects]]
    from = "/docs/libraries/js"
    to = "/docs/integrate/client/js"

# Added: 2021-07-13
[[redirects]]
    from = "/docs/libraries/react-native"
    to = "/docs/integrate/client/react-native"

# Added: 2021-07-13
[[redirects]]
    from = "/docs/deployment/snippet-installation"
    to = "/docs/integrate/client/snippet-installation"

# Added: 2021-07-13
[[redirects]]
    from = "/docs/libraries/elixir"
    to = "/docs/integrate/server/elixir"

# Added: 2021-07-13
[[redirects]]
    from = "/docs/libraries/go"
    to = "/docs/integrate/server/go"

# Added: 2021-07-13
[[redirects]]
    from = "/docs/libraries/node"
    to = "/docs/integrate/server/node"

# Added: 2021-07-13
[[redirects]]
    from = "/docs/libraries/php"
    to = "/docs/integrate/server/php"

# Added: 2021-07-13
[[redirects]]
    from = "/docs/libraries/python"
    to = "/docs/integrate/server/python"

# Added: 2021-07-13
[[redirects]]
    from = "/docs/libraries/ruby"
    to = "/docs/integrate/server/ruby"

# Added: 2021-07-13
[[redirects]]
    from = "/docs/libraries/docusaurus"
    to = "/docs/integrate/third-party/docusaurus"

# Added: 2021-07-13
[[redirects]]
    from = "/docs/libraries/gatsby"
    to = "/docs/integrate/third-party/gatsby"

# Added: 2021-07-13
[[redirects]]
    from = "/docs/tutorials/1-minute/integrate-with-gtm"
    to = "/docs/integrate/third-party/google-tag-manager"

# Added: 2021-07-13
[[redirects]]
    from = "/docs/tutorials/1-minute/integrate-with-metabase"
    to = "/docs/integrate/third-party/metabase"

# Added: 2021-07-13
[[redirects]]
    from = "/docs/tutorials/1-minute/integrate-with-nuxt-js"
    to = "/docs/integrate/third-party/nuxt-js"

# Added: 2021-07-13
[[redirects]]
    from = "/docs/tutorials/1-minute/integrate-with-retool"
    to = "/docs/integrate/third-party/retool"

# Added: 2021-07-13
[[redirects]]
    from = "/docs/libraries/rudderstack"
    to = "/docs/integrate/third-party/rudderstack"

# Added: 2021-07-13
[[redirects]]
    from = "/docs/libraries/segment"
    to = "/docs/integrate/third-party/segment"

# Added: 2021-07-13
[[redirects]]
    from = "/docs/libraries/sentry"
    to = "/docs/integrate/third-party/sentry"

# Added: 2021-07-13
[[redirects]]
    from = "/docs/tutorials/1-minute/integrate-with-shopify"
    to = "/docs/integrate/third-party/shopify"

# Added: 2021-07-13
[[redirects]]
    from = "/docs/tutorials/1-minute/integrate-with-wordpress"
    to = "/docs/integrate/third-party/wordpress"

# Added: 2021-07-13
[[redirects]]
    from = "/docs/libraries/message-formatting"
    to = "/docs/integrate/webhooks/message-formatting"

# Added: 2021-07-13
[[redirects]]
    from = "/docs/libraries/microsoft-teams"
    to = "/docs/integrate/webhooks/microsoft-teams"

# Added: 2021-07-13
[[redirects]]
    from = "/docs/libraries/slack"
    to = "/docs/integrate/webhooks/slack"

# Added: 2021-07-13
[[redirects]]
    from = "/docs/configuring-posthog/email"
    to = "/docs/self-host/configure/email"

# Added: 2021-07-13
[[redirects]]
    from = "/docs/configuring-posthog/environment-variables"
    to = "/docs/self-host/configure/environment-variables"

# Added: 2021-07-13
[[redirects]]
    from = "/docs/configuring-posthog/running-behind-proxy"
    to = "/docs/self-host/configure/running-behind-proxy"

# Added: 2021-07-13
[[redirects]]
    from = "/docs/configuring-posthog/securing-posthog"
    to = "/docs/self-host/configure/securing-posthog"

# Added: 2021-07-13
[[redirects]]
    from = "/docs/configuring-posthog/upgrading-posthog"
    to = "/docs/self-host/configure/upgrading-posthog"

# Added: 2021-07-13
[[redirects]]
    from = "/docs/deployment/deploy-aws-clickhouse"
    to = "/docs/self-host/deploy/aws-clickhouse"

# Added: 2021-07-13
[[redirects]]
    from = "/docs/deployment/deploy-aws"
    to = "/docs/self-host/deploy/aws"

# Added: 2021-07-13
[[redirects]]
    from = "/docs/deployment/deploy-azure"
    to = "/docs/self-host/deploy/azure"

# Added: 2021-07-13
[[redirects]]
    from = "/docs/deployment/deploy-digital-ocean"
    to = "/docs/self-host/deploy/digital-ocean"

# Added: 2021-07-13
[[redirects]]
    from = "/docs/deployment/deploy-docker"
    to = "/docs/self-host/deploy/docker"

# Added: 2021-07-13
[[redirects]]
    from = "/docs/deployment/deploy-gke-clickhouse"
    to = "/docs/self-host/deploy/gke-clickhouse"

# Added: 2021-07-13
[[redirects]]
    from = "/docs/deployment/deploy-gcs"
    to = "/docs/self-host/deploy/google-cloud-services"

# Added: 2021-07-13
[[redirects]]
    from = "/docs/deployment/deploy-heroku"
    to = "/docs/self-host/deploy/heroku"

# Added: 2021-07-13
[[redirects]]
    from = "/docs/deployment/hosting-costs"
    to = "/docs/self-host/deploy/hosting-costs"

# Added: 2021-07-13
[[redirects]]
    from = "/docs/deployment/deploy-kubernetes"
    to = "/docs/self-host/deploy/kubernetes"

# Added: 2021-07-13
[[redirects]]
    from = "/docs/deployment/deploy-proxy"
    to = "/docs/self-host/deploy/proxy"

# Added: 2021-07-13
[[redirects]]
    from = "/docs/deployment/deploy-qovery"
    to = "/docs/self-host/deploy/qovery"

# Added: 2021-07-13
[[redirects]]
    from = "/docs/deployment/deploy-render"
    to = "/docs/self-host/deploy/render"

# Added: 2021-07-13
[[redirects]]
    from = "/docs/deployment/deploy-source"
    to = "/docs/self-host/deploy/source"

# Added: 2021-07-13
[[redirects]]
    from = "/docs/configuring-posthog/deleting-data"
    to = "/docs/tutorials/deleting-data"

# Added: 2021-07-13
[[redirects]]
    from = "/docs/features/actions"
    to = "/docs/user-guides/actions"

# Added: 2021-07-13
[[redirects]]
    from = "/docs/features/annotations"
    to = "/docs/user-guides/annotations"

# Added: 2021-07-13
[[redirects]]
    from = "/docs/application-settings"
    to = "/docs/user-guides/application-settings"

# Added: 2021-07-13
[[redirects]]
    from = "/docs/features/cohorts"
    to = "/docs/user-guides/cohorts"

# Added: 2021-07-13
[[redirects]]
    from = "/docs/features/dashboards"
    to = "/docs/user-guides/dashboards"

# Added: 2021-07-13
[[redirects]]
    from = "/docs/features/events"
    to = "/docs/user-guides/events"

# Added: 2021-07-13
[[redirects]]
    from = "/docs/features/feature-flags"
    to = "/docs/user-guides/feature-flags"

# Added: 2021-07-13
[[redirects]]
    from = "/docs/features/funnels"
    to = "/docs/user-guides/funnels"

# Added: 2021-07-13
[[redirects]]
    from = "/docs/features/organizations"
    to = "/docs/user-guides/organizations"

# Added: 2021-07-13
[[redirects]]
    from = "/docs/features/paths"
    to = "/docs/user-guides/paths"

# Added: 2021-07-13
[[redirects]]
    from = "/docs/features/plugins"
    to = "/docs/user-guides/plugins"

# Added: 2021-07-13
[[redirects]]
    from = "/docs/features/projects"
    to = "/docs/user-guides/projects"

# Added: 2021-07-13
[[redirects]]
    from = "/docs/features/retention"
    to = "/docs/user-guides/retention"

# Added: 2021-07-13
[[redirects]]
    from = "/docs/features/session-recording"
    to = "/docs/user-guides/session-recording"

# Added: 2021-07-13
[[redirects]]
    from = "/docs/features/sessions"
    to = "/docs/user-guides/sessions"

# Added: 2021-07-13
[[redirects]]
    from = "/docs/features/toolbar"
    to = "/docs/user-guides/toolbar"

# Added: 2021-07-13
[[redirects]]
    from = "/docs/features/trends"
    to = "/docs/user-guides/trends"

# Added: 2021-07-13
[[redirects]]
    from = "/docs/features/users"
    to = "/docs/user-guides/users"

# Added: 2021-07-13
[[redirects]]
    from = "/docs/tutorials"
    to = "/docs/tutorials/overview"

# Added: 2021-07-13
[[redirects]]
    from = "/docs/features"
    to = "/docs/user-guides/overview"

# Added: 2021-07-13
[[redirects]]
    from = "/docs/tutorials/1-minute/survey"
    to = "/docs/tutorials/survey"

# Added: 2021-07-14
# Not due to a rename, but to improve the website's navigation experience
[[redirects]]
    from = "/features"
    to = "/product"

# Added: 2021-07-16
[[redirects]]
    from = "/docs/integrate"
    to = "/docs/integrate/overview"

# Added: 2021-07-16
[[redirects]]
    from = "/docs/integrations"
    to = "/docs/integrate/overview"

# Added: 2021-07-16
[[redirects]]
    from = "/docs/libraries"
    to = "/docs/integrate/overview"
    
# Added: 2021-07-17
# Not due to a rename, but to improve the website's navigation experience
[[redirects]]
    from = "/signup"
    to = "/pricing"

# Added: 2021-07-21
# Not due to a rename, but to improve the website's navigation experience
[[redirects]]
    from = "/product-features"
    to = "/product"

# Added: 2021-08-06
[[redirects]]
    from = "/docs/api/index"
    to = "/docs/api/overview"

# Added: 2021-08-06
[[redirects]]
    from = "/docs/contribute/index"
    to = "/docs/contribute/overview"

# Added: 2021-08-06
[[redirects]]
    from = "/docs/data-model"
    to = "/docs/data-model"

# Added: 2021-08-06
[[redirects]]
    from = "/docs/integrate/client/android/index"
    to = "/docs/integrate/client/android"

# Added: 2021-08-06
[[redirects]]
    from = "/docs/integrate/client/flutter/snippets/install"
    to = "/docs/integrate/client/flutter"

# Added: 2021-08-06
[[redirects]]
    from = "/docs/integrate/client/ios/index"
    to = "/docs/integrate/client/ios"

# Added: 2021-08-06
[[redirects]]
    from = "/docs/integrate/client/js/index"
    to = "/docs/integrate/client/js"

# Added: 2021-08-06
[[redirects]]
    from = "/docs/integrate/index"
    to = "/docs/integrate/overview"

# Added: 2021-08-06
[[redirects]]
    from = "/docs/plugins/build/index"
    to = "/docs/plugins/build/overview"

# Added: 2021-08-06
[[redirects]]
    from = "/docs/plugins/index"
    to = "/docs/plugins/overview"

# Added: 2021-08-06
[[redirects]]
    from = "/docs/self-host/index"
    to = "/docs/self-host/overview"

# Added: 2021-08-06
[[redirects]]
    from = "/docs/tutorials/event-tracking-guide"
    to = "/docs/tutorials/actions"

# Added: 2021-08-06
[[redirects]]
    from = "/docs/tutorials/index"
    to = "/docs/tutorials/overview"

# Added: 2021-08-06
[[redirects]]
    from = "/docs/user-guides/index"
    to = "/docs/user-guides/overview"
